export const ADDRESS_ADD_FAILURE="ADDRESS_ADD_FAILURE"
export const ADDRESS_ADD_PENDING="ADDRESS_ADD_PENDING"
export const ADDRESS_ADD_SUCCESS="ADDRESS_ADD_SUCCESS"


export const ADDRESS_GET_FAILURE="CARTADDRESS_FAILURE"
export const ADDRESS_GET_PENDING="CARTADDRESS_PENDING"
export const ADDRESS_GET_SUCCESS="CARTADDRESS_SUCCESS"


export const ADDRESS_DELETE_FAILURE="ADDRESS_DELETE_FAILURE"
export const ADDRESS_DELETE_PENDING="ADDRESS_DELETE_PENDING"
export const ADDRESS_DELETE_SUCCESS="ADDRESS_DELETE_SUCCESS"


