


export const CART_ADD_FAILURE="CART_ADD_FAILURE"
export const CART_ADD_PENDING="CART_ADD_PENDING"
export const CART_ADD_SUCCESS="CART_ADD_SUCCESS"


export const CART_GET_FAILURE="CART_GET_FAILURE"
export const CART_GET_PENDING="CART_GET_PENDING"
export const CART_GET_SUCCESS="CART_GET_SUCCESS"


export const CART_DELETE_FAILURE="CART_DELETE_FAILURE"
export const CART_DELETE_PENDING="CART_DELETE_PENDING"
export const CART_DELETE_SUCCESS="CART_DELETE_SUCCESS"