


export const USER_LOGIN_FAILURE="USER_LOGIN_FAILURE"
export const USER_LOGIN_PENDING="USER_LOGIN_PENDING"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"

export const USER_REGISTER_FAILURE="USER_REGISTER_FAILURE"
export const USER_REGISTER_PENDING="USER_REGISTER_PENDING"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"


export const USER_DELETE_FAILURE="USER_DELETE_FAILURE"
export const USER_DELETE_PENDING="USER_DELETE_PENDING"
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS"



export const USER_GET_FAILURE="USER_GET_FAILURE"
export const USER_GET_PENDING="USER_GET_PENDING"
export const USER_GET_SUCCESS="USER_GET_SUCCESS"


export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"

export const SINGLE_USER_SUCCESS="SINGLE_USER_SUCCESS"