



export const PRODUCT_GET_FAILURE="PRODUCT_GET_FAILURE"
export const PRODUCT_GET_PENDING="PRODUCT_GET_PENDING"
export const PRODUCT_GET_SUCCESS="PRODUCT_GET_SUCCESS"


export const SINGLE_PRODUCT_GET_FAILURE="SINGLE_PRODUCT_GET_FAILURE"
export const SINGLE_PRODUCT_GET_PENDING="SINGLE_PRODUCT_GET_PENDING"
export const SINGLE_PRODUCT_GET_SUCCESS="SINGLE_PRODUCT_GET_SUCCESS"