



export const PRODUCT_GET_FAILURE = "PRODUCT_GET_FAILURE"
export const PRODUCT_GET_PENDING = "PRODUCT_GET_PENDING"
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"


export const PRODUCT_POST_FAILURE = "PRODUCT_POST_FAILURE"
export const PRODUCT_POST_PENDING = "PRODUCT_POST_PENDING"
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS"

export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE"
export const PRODUCT_DELETE_PENDING = "PRODUCT_DELETE_PENDING"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"


export const PRODUCT_EDIT_FAILURE = "PRODUCT_EDIT_FAILURE"
export const PRODUCT_EDIT_PENDING = "PRODUCT_EDIT_PENDING"
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS"



export const SINGLE_PRODUCT_GET_FAILURE = "SINGLE_PRODUCT_GET_FAILURE"
export const SINGLE_PRODUCT_GET_PENDING = "SINGLE_PRODUCT_GET_PENDING"
export const SINGLE_PRODUCT_GET_SUCCESS = "SINGLE_PRODUCT_GET_SUCCESS"